[package]
name = "nae"
version = "0.1.0"
authors = ["Nazariglez <nazari.nz@gmail.com>"]
edition = "2018"

#[lib]
#crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1.29"
nae-derive = { path = "./nae-derive" }
nae-core = { path = "./nae-core" }
backend = { path = "./nae-backend", package = "nae-backend" }

[features]
default = ["extras"]
extras = []

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen = "0.2.51"

[workspace]
members = [
    "nae-derive",
    "nae-core",
    "nae-glow",
    "nae-web",
    "nae-native",
    "nae-backend"
]
