[package]
name = "nae"
version = "0.1.0"
authors = ["Nazariglez <nazari.nz@gmail.com>"]
edition = "2018"

#[lib]
#crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.3.0-alpha2"
wasm-bindgen = "0.2.51"
console_error_panic_hook = "0.1.6"
nalgebra-glm = "0.4.2"
lyon = "0.14.1"
rayon = "1.2.0"
futures = "0.1.29"
wasm-bindgen-futures = "0.3"
js-sys = "0.3.30"
image = "0.22.3"
rand = "0.7.2"
hashbrown = "0.6.3"
vek = "0.9.10"
nae-derive = { path = "./nae-derive" }
nae-core = { path = "./nae-core" }
glyph_brush = "0.6.1"

[dependencies.web-sys]
version = "0.3.28"
#package = "web_sys"
features = [
    "console",
    "Document",
    "Window",
    "HtmlCanvasElement",
    'HtmlImageElement',
  'XmlHttpRequest',
  'XmlHttpRequestEventTarget',
  'XmlHttpRequestResponseType',
  'WebGlContextAttributes'
]

[features]

[dev-dependencies]
wasm-bindgen = "0.2.51"

[workspace]
members = [
    "nae-derive",
    "nae-core",
    "nae-glow",
    "nae-web"
]
