[package]
name = "nae"
version = "0.1.0"
authors = ["Nazariglez <nazari.nz@gmail.com>"]
edition = "2018"

#[lib]
#crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1.29"
nae-derive = { path = "./nae-derive" }
nae-core = { path = "./nae-core" }
backend = { path = "./nae-backend", package = "nae-backend" }
nae-gfx = { path = "./nae-gfx" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hashbrown = "0.6.3"

[features]
default = ["winit"]
winit = ["backend/winit_win"]
sdl = ["backend/sdl"]

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen = "0.2.51"

[dev-dependencies]
nalgebra-glm = "0.4.2"
specs = { version = "0.16.1", default-features = false }

[workspace]
members = [
    "nae-derive",
    "nae-core",
    "nae-backend",
    "nae-gfx",
    "nae-shader"
]

[profile.release]
lto = true

