[package]
name = "notan_app"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.9"
notan_log = { path = "../notan_log" }
downcast-rs = "1.2"
indexmap = "1.6.0"
