[package]
name = "notan_macro"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
bevy-glsl-to-spirv = "0.2.1"
glsl-to-spirv = "0.1.7"
proc-macro2 = "1.0.24"
spirv_cross = { version = "0.22.1", features = ["glsl"] }

[lib]
proc-macro = true