[package]
name = "notan"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notan_app = { path = "./crates/notan_app" }
notan_derive = { path = "./crates/notan_derive" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
notan_web = { path = "./crates/notan_web" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
notan_winit = { path = "./crates/notan_winit" }

[workspace]
members = ["crates/*"]