[package]
name = "nae-derive"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
syn = { version = "0.15", features = ["full"] }
quote = "0.6"

[lib]
proc-macro = true