[package]
name = "notan_glyph"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glyph_brush = "0.7.2"
notan_log = { path = "../notan_log" }
notan_graphics = { path = "../notan_graphics" }
notan_macro = { path = "../notan_macro" }
glam = "0.16.0"

[features]
default = ["default_render"]
default_render = []